services:
  backend:
    build:
      context: .
      dockerFile: dockerfile
    command:
      [
        'sh',
        '-c',
        'npx prisma generate && npx prisma db push && yarn start:prod',
      ]
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17.5
    container_name: youtube_clone_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: youtube_clone_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
  nginx:
    image: nginx:latest
    container_name: youtube_clone_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/uploads:ro
      - ~/certs:/etc/nginx/certs:ro
    depends_on:
      - backend

volumes:
  pgdata:
