services:
  backend:
    build:
      context: .
    command: ['sh', '-c', 'npx prisma db push && yarn start:prod']
    ports:
      - '${PORT}:${PORT}'  
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17.5
    container_name: youtube_clone_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: youtube_clone_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  pgdata:
